cache_location = "cache/"
report_location = "reports/"
data_path = "data/Data V2/"
keyword_path = "data/Data keywords/"
kv_model = "glove-wiki-gigaword-50"
automated_account_id = "4b5f8672-2180-4507-a694-4926e0da7f83"
unhashing_enabled = true
task_pipe_enabled = true
wordvec_pipe_enabled = false
countvec_pipe_enabled = true
test_size = 0.33
grid_search_enabled = false
max_recommendations = 5