cache_location = "cache/"
report_location = "reports/"
data_path = "data/Data V2/"
keyword_path = "data/Data keywords/"
kv_model = "glove-wiki-gigaword-50"
unhashing_enabled = true
task_pipe_enabled = true
wordvec_pipe_enabled = false
countvec_pipe_enabled = true
stemming_enabled = true
test_size = 0.15
cv_folds = 3
cv_scoring = "roc_auc_ovr"
min_class_frequency = 10
max_recommendations = 5